import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from 'components/Layout';
import PlanetList from 'components/PlanetList';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Planet App</title>
        <meta name="description" content="Generated by Planet App" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        <PlanetList />
      </Layout>
    </div>
  );
};

export default Home;
